### PR TITLE
Delayed alert fixes

### PR DESCRIPTION
**Pull request by bam95899**

### CODE REVIEW

**Comment by c-schwarze** [comment]
I'd say wait to merge, until @j-jasik takes a look.

**Comment by j-jasik** [comment]
Well I've spent some time with this myself and I can confirm that it is working. Currently, no alert gets displayed when a session is created, but when I switch to this branch and create, an alert is shown as expected. Also it doesn't appear to be affect the alert on other pages. I'm not sure why this is fixing the issue though, and because of that I'm reluctant to just blindly merge it in. Maybe the next time @c-schwarze is in we can chat about it.

**Comment by c-schwarze** [comment]
Jordan and I talked about this. It seems odd that this actually fixes the issue. @j-jasik is going to look into this a bit more to see if we can find an alternative solution

**Comment by j-jasik** [comment]
Awesome, this looks great, and we understand what's happening now. We moved away from using redirects because for some reason they were causing the alert to be cleared.

**Comment by c-schwarze** [comment]
Nice job working through this one guys 👍

**Pull request merged**
